Sdk updates
arcalot/arcaflow-plugin-uperf pull request #48
Opened 2024-04-11 21:07 UTC by mfleader

## Changes introduced with this PR

Update schema to use `discriminator_inlined=True`.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2024-04-11 22:57 UTC, jaredoconnell approved these changes

2024-04-12 15:20 UTC, webbnh requested changes
Is that the correct plugin?  (I _think_ that's the one I was talking about wanting to _delete_, yesterday....)

2024-04-12 15:20 UTC, webbnh commented on pyproject.toml
> +arcaflow-plugin-sdk = "~0.14.0.dev1"
Is this the correct reference??  Shouldn't it be `0.14.0.b1`?

2024-04-12 19:21 UTC, webbnh commented on pyproject.toml
> +arcaflow-plugin-sdk = "~0.14.0.dev1"
So, this should now be `0.14.1`!  😁

2024-04-12 20:17 UTC, webbnh approved these changes
👍

2024-04-12 20:18 UTC, webbnh approved these changes
🚂

2024-04-12 20:22 UTC, jaredoconnell approved these changes

2024-04-12 20:24 UTC, merged